[package]
name = "BucketOracle"
version = "0.0.2"

[dependencies]
Sui = { local = "D:/envs/move/sui/sui/crates/sui-framework/packages/sui-framework" }
SwitchboardStdLib = { local = "./partners/switchboard" }
Pyth = { local = "./partners/pyth" }
SupraOracle = { local = "./partners/supra" }

[addresses]
bucket_oracle = "0x0"
sui =  "0000000000000000000000000000000000000000000000000000000000000002"